name: Analysis Tool For HyperOS

on:
  workflow_dispatch:
    inputs:
      link:
        description: "ROM 链接"
        required: true
      push:
        description: "上传数据库"
        required: true
        type: choice
        options:
        - "是"
        - "否"
      devicename:
        description: "设备名"
        required: false
      osversion:
        description: "系统版本"
        required: false

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependence
      run: |
        pip install -r requirements.txt

    - name: Set permission
      run: |
       chmod +x ./tools/Linux/x86_64/extract.erofs
       chmod +x ./tools/Linux/x86_64/payload-dumper-go

    - name: Download ROM
      run: |
        python main.py -d "${{ github.event.inputs.link }}"

    - name: Unzip payload.bin
      run: |
        python main.py -p
        rm *.zip

    - name: Unzip img
      run: |
        python main.py -i
        rm payload.bin
    
    - name: Unzip file
      run: |
        python main.py -f

    - name: Remove exclude apk
      run: |
        python main.py -a

    - name: Upload special apk
      uses: actions/upload-artifact@v4
      with:
        name: Special_apk
        path: |
          output_apk/OplusLanuncher.apk
          output_apk/Settings.apk
          output_apk/Battery.apk
          output_apk/PhoneManager.apk
                  
    - name: Get version
      run: |
        python main.py -n

    - name: Update database
      run: |
        python main.py -u

    - name: Upload build.prop
      uses: actions/upload-artifact@v4
      with:
        name: build.prop
        path: |
          /my_product/build.prop

    - name: Rename
      run: |
        python main.py -m

    - name: Upload database
      uses: actions/upload-artifact@v4
      with:
        name: Database
        path: |
          app_version.json
          app_code.json
    
    - name: Upload update apk
      uses: actions/upload-artifact@v4
      with:
        name: Update_apk
        path: |
          update_apk
          update_name_apk

    - name: Push database
      continue-on-error: true
      run: |
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --global user.name "${GITHUB_ACTOR}"
        git add app_version.json app_code.json
        if [ "${{ github.event.inputs.push }}" = "是" ]; then
            git commit -m "chore: update ${{ github.event.inputs.devicename }} ${{ github.event.inputs.osversion }} by action"
            git push
          elif [ "${{ github.event.inputs.push }}" = "否" ]; then
            exit 0
          else
            exit 0
          fi

    - name: Get Info
      continue-on-error: true
      run: |
        python main.py -o
