name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Release Notes
        id: release-notes
        run: |
          # 获取当前标签
          currentTag=$(git describe --tags --exact-match)
          
          # 获取前一个标签
          previousTag=$(git describe --tags "$(git rev-list --tags --skip=1 --max-count=1)" || echo "")
          
          # 如果没有前一个标签，仅显示当前标签的所有提交
          if [ -z "$previousTag" ]; then
            release_notes="## What's Changed</br>$(git log --pretty=format:"* %s" "$currentTag")"
          else
            release_notes="## What's Changed</br>$(git log --pretty=format:"* %s" "$previousTag..$currentTag")"
          fi
          
          # 设置输出变量
          echo "release_notes<<EOF" >> $GITHUB_ENV
          echo "$release_notes" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ env.release_notes }}
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
